databases:
  - name: outline-wiki-postgresql
    databaseName: outline
    user: outline
    plan: starter
    region: singapore
    ipAllowList: []

services:
- type: redis
    name: outline-wiki-redis
    plan: starter
    region: singapore
    ipAllowList: []
- type: web
  region: singapore
  plan: starter
  name: outline-wiki-minio
  healthCheckPath: /minio/health/live
  env: docker
  dockerfilePath: ./minio/Dockerfile
  dockerContext: .
  autoDeploy: false
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: PORT
    value: 10000
- type: web
  plan: starter
  region: singapore
  name: outline-wiki
  env: docker
  dockerfilePath: ./docker-outline/Dockerfile
  autoDeploy: false
  disk:
    name: outline-persistent-storage
    mountPath: /data
    sizeGB: 5
  envVars:
    - key: URL
      sync: false
    - key: NODE_ENV
      value: 'production'
    - key: SECRET_KEY
      generateValue: true
    - key: UTILS_SECRET
      generateValue: true
    - key: SMTP_HOST
      value: 'smtp.sendgrid.net'
    - key: SMTP_PORT
      value: 587
    - key: SMTP_USERNAME
      value: 'apikey'
    - key: SMTP_PASSWORD
      sync: false
    - key: SMTP_FROM_EMAIL
      sync: false
    - key: SMTP_REPLY_EMAIL
      sync: false
    - key: DATABASE_URL
      fromDatabase:
        name: outline-wiki-postgresql
        property: connectionString


